#!/bin/bash

write_zshrc() {
    write_file "$TARGET_HOME/.zshrc" "0644" "" <<EOF
# Generated by FluxEnv

export PATH="\$HOME/bin:/usr/local/bin:\$PATH"
export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8
export FLUXENV_PROMPT_HOST="${HOST_NAME}"

alias ll='ls -lh --color=auto'
alias grep='grep --color=auto'

if command -v starship >/dev/null 2>&1; then
    eval "\$(starship init zsh)"
fi

autoload -Uz compinit
compinit

[ -f ~/.zsh/plugins/zsh-autosuggestions/zsh-autosuggestions.zsh ] && source ~/.zsh/plugins/zsh-autosuggestions/zsh-autosuggestions.zsh
[ -f ~/.zsh/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh ] && source ~/.zsh/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
EOF
}

write_starship_config() {
    local docker_format='$hostname'
    local docker_hostname_block='[hostname]
ssh_only = false
format = "@[\$hostname](\$style) "
trim_at = "."
style = "cyan"'

    if [ "$VISUAL_HOSTNAME_ONLY" -eq 1 ]; then
        docker_format='${custom.hostname_override}'
        docker_hostname_block='[custom.hostname_override]
command = "printf %s \"$FLUXENV_PROMPT_HOST\""
when = "test -n \"$FLUXENV_PROMPT_HOST\""
format = "@[$output](cyan) "'
    fi

    if [ "${STARSHIP_PRESET:-bare-metal}" = "docker" ]; then
        write_file "$TARGET_HOME/.config/starship.toml" "0644" "" <<EOF
format = """
\${custom.user}${docker_format}\$directory\$git_branch\$git_status\$python
\$character
"""

command_timeout = 2000

[custom.user]
command = "echo 🐳"
when = "true"
style = "cyan bold"
format = "[🐳](\$style)"

${docker_hostname_block}

[python]
detect_extensions = ["py", "ipynb", "pyproject.toml"]
format = '([\$symbol\$virtualenv](\$style) )'
style = "yellow bold"
symbol = " "

[directory]
style = "yellow"
truncation_length = 4
truncation_symbol = "…/"
format = "[\$path](\$style)[\$read_only](\$read_only_style) "

[git_branch]
symbol = ""
style = "purple bold"
format = "[\$symbol\$branch](\$style)"

[git_status]
disabled = false
format = ' ([\$all_status\$ahead_behind](\$style) )'
style = "red bold"
staged = "[+](green) "
modified = "[!](red) "
untracked = "[?](yellow) "
deleted = "[✘](red) "
renamed = "[»](yellow) "
conflicted = "[=](red bold) "
stashed = "[$](cyan) "
ahead = "⇡"
behind = "⇣"
diverged = "⇕"
up_to_date = ""

[conda]
disabled = false
ignore_base = false
style = "#78E08F bold"
symbol = ""
format = "[\\(\$symbol\$environment\\)](\$style) "

[custom.conda_filter]
command = "if [ \"\$CONDA_DEFAULT_ENV\" = \".docker\" ]; then echo ''; else echo \"\$CONDA_DEFAULT_ENV\"; fi"
style = "green bold"
format = "([\$output](\$style)) "
when = "echo true"

[character]
success_symbol = "[❯](white bold)"
error_symbol = "[❯](red bold)"
vimcmd_symbol = "[❮](green bold)"
EOF
    else
        write_file "$TARGET_HOME/.config/starship.toml" "0644" "" <<EOF
# ~/.config/starship.toml

# 1. 配置用户名 (User)
[username]
style_user = "yellow bold"
style_root = "red bold"
format = "[\$user](\$style)"
show_always = true

# 2. 配置主机名 (Hostname)
[hostname]
ssh_only = false
format = "@[\$hostname](\$style) "
trim_at = "."
style = "cyan"

# 3. 禁用编程语言环境显示
[python]
disabled = false
symbol = " "

[java]
symbol = " "
style = "yellow"

[nodejs]
disabled = true

[golang]
disabled = true

# =======================
# 2. 路径 (视觉焦点)
# =======================
[directory]
style = "yellow"
truncation_length = 4
truncation_symbol = "…/"
format = "[\$path](\$style)[\$read_only](\$read_only_style) "

# =======================
# 3. Git 状态 (优雅点缀)
# =======================
[git_branch]
symbol = ""
style = "purple bold"
format = "[\$symbol\$branch](\$style)"

[git_status]
disabled = false
format = ' ([\$all_status\$ahead_behind](\$style) )'
style = "red bold"
staged = "[+](green) "
modified = "[!](red) "
untracked = "[?](yellow) "
deleted = "[✘](red) "
renamed = "[»](yellow) "
conflicted = "[=](red bold) "
stashed = "[$](cyan) "
ahead = "⇡"
behind = "⇣"
diverged = "⇕"
up_to_date = ""

# =======================
# 4. Conda 环境 (重写标识)
# =======================
[conda]
disabled = false
ignore_base = false
style = "#78E08F bold"
symbol = ""
format = "[\\(\$symbol\$environment\\)](\$style) "

# =======================
# 5. 提示符 (灵动指针)
# =======================
[character]
success_symbol = "[❯](white bold)"
error_symbol = "[❯](red bold)"
vimcmd_symbol = "[❮](green bold)"
EOF
    fi
}

install_plugin_dir() {
    local plugin_name="$1"
    local source_dir="$OFFLINE_DIR/$plugin_name"
    local target_dir="$TARGET_HOME/.zsh/plugins/$plugin_name"
    local remote_url="$2"

    if [ -d "$source_dir" ]; then
        remove_path "$target_dir"
        copy_path "$source_dir" "$target_dir"
        return 0
    fi

    if [ "$ALLOW_ONLINE_FETCH" -eq 1 ]; then
        run_cmd "在线克隆 ${plugin_name}" git clone --depth=1 "$remote_url" "$target_dir"
        return 0
    fi

    warn "缺少离线资源: $plugin_name，且 ALLOW_ONLINE_FETCH=0"
}

step_user() {
    stage "用户配置"

    if [ "$CREATE_USER" -eq 0 ]; then
        TARGET_USER="${TARGET_USER:-root}"
        TARGET_HOME="${TARGET_HOME:-$(get_user_home "$TARGET_USER")}"
        progress "当前 profile 使用现有用户: $TARGET_USER"
        return 0
    fi

    prompt_value USER_NAME "请输入用户名（字母开头，可含数字和下划线）" '^[a-zA-Z][a-zA-Z0-9_]*$'
    prompt_password USER_PASSWORD "请设置用户密码"

    if id "$USER_NAME" >/dev/null 2>&1; then
        if [ "$FORCE_RECREATE_USER" -eq 1 ] || prompt_yes_no "用户 $USER_NAME 已存在，是否删除并重新创建？" "n"; then
            run_cmd "删除旧用户 $USER_NAME" userdel -rf "$USER_NAME"
        else
            die "用户已存在，已终止。可设置 FORCE_RECREATE_USER=1"
        fi
    fi

    run_cmd "创建用户 $USER_NAME" useradd "$USER_NAME" -G sudo -m -s /bin/zsh
    run_shell "设置用户密码" "printf '%s:%s\n' '$USER_NAME' '$USER_PASSWORD' | chpasswd"

    TARGET_USER="$USER_NAME"
    TARGET_HOME="$(get_user_home "$TARGET_USER")"
}

step_sudo() {
    stage "Sudo 临时权限配置"

    if [ "$ENABLE_TEMP_SUDO" -ne 1 ]; then
        progress "当前 profile 跳过临时 sudo 配置"
        return 0
    fi

    backup_path /etc/sudoers
    write_file /etc/sudoers.d/temp_install "0440" "" <<'EOF'
%sudo ALL=(ALL:ALL) NOPASSWD: ALL
Defaults visiblepw
EOF
}

step_shell_env() {
    stage "Shell 环境配置"

    run_cmd "创建 shell 配置目录" mkdir -p "$TARGET_HOME/.zsh/plugins" "$TARGET_HOME/.config" "$TARGET_HOME/bin"

    if [ -f "$OFFLINE_DIR/starship-x86_64-unknown-linux-gnu.tar.gz" ]; then
        run_shell "安装 Starship 离线二进制" "tmpdir=\$(mktemp -d) && tar -xzf '$OFFLINE_DIR/starship-x86_64-unknown-linux-gnu.tar.gz' -C \"\$tmpdir\" && install -m 0755 \"\$tmpdir/starship\" /usr/local/bin/starship && rm -rf \"\$tmpdir\""
        STARSHIP_INSTALLED=1
    elif [ -f "$OFFLINE_DIR/starship_install.sh" ]; then
        run_cmd "执行本地 Starship 安装脚本" bash "$OFFLINE_DIR/starship_install.sh" -y
        STARSHIP_INSTALLED=1
    elif [ "$ALLOW_ONLINE_FETCH" -eq 1 ]; then
        run_shell "在线安装 Starship" "curl -sS https://starship.rs/install.sh | sh -s -- -y"
        STARSHIP_INSTALLED=1
    else
        warn "缺少 Starship 离线资源，已跳过安装"
    fi

    install_plugin_dir "zsh-autosuggestions" "https://github.com/zsh-users/zsh-autosuggestions"
    install_plugin_dir "zsh-syntax-highlighting" "https://github.com/zsh-users/zsh-syntax-highlighting"

    if [ -f "$TARGET_HOME/.zshrc" ]; then
        backup_path "$TARGET_HOME/.zshrc"
    fi
    if [ -f "$TARGET_HOME/.config/starship.toml" ]; then
        backup_path "$TARGET_HOME/.config/starship.toml"
    fi

    write_zshrc
    write_starship_config

    if [ "$TARGET_USER" != "root" ] && [ "${DRY_RUN:-0}" -eq 0 ]; then
        chown -R "$TARGET_USER:$TARGET_USER" "$TARGET_HOME/.zsh" "$TARGET_HOME/.config" "$TARGET_HOME/.zshrc" "$TARGET_HOME/bin"
    fi

    if [ "$CHANGE_DEFAULT_SHELL" -eq 1 ] && command_exists zsh; then
        try_cmd "设置默认 shell 为 zsh" chsh -s "$(command -v zsh)" "$TARGET_USER"
    fi
}

step_vim() {
    stage "Vim 配置"

    resolve_toggle ENABLE_VIM "是否配置 Vim 编辑器？" "n"
    VIM_ENABLED="$ENABLE_VIM"
    if [ "$VIM_ENABLED" -ne 1 ]; then
        progress "跳过 Vim 配置"
        return 0
    fi

    try_shell "安装 Vim 相关软件包" "DEBIAN_FRONTEND=noninteractive apt install -y vim xclip astyle python3-setuptools"

    if [ -d "$TARGET_HOME/.vim" ]; then
        backup_path "$TARGET_HOME/.vim"
    fi
    if [ -f "$TARGET_HOME/.vimrc" ]; then
        backup_path "$TARGET_HOME/.vimrc"
    fi

    if [ "$VIM_MODE" = "full" ] && [ -d "$OFFLINE_DIR/vim" ]; then
        remove_path "$TARGET_HOME/.vim"
        copy_path "$OFFLINE_DIR/vim" "$TARGET_HOME/.vim"
        if [ -f "$TARGET_HOME/.vim/.vimrc" ] && [ "${DRY_RUN:-0}" -eq 0 ]; then
            cp "$TARGET_HOME/.vim/.vimrc" "$TARGET_HOME/.vimrc"
        fi
    else
        write_file "$TARGET_HOME/.vimrc" "0644" "" <<'EOF'
set number
set mouse=a
set smartindent
set tabstop=4
set expandtab
syntax on
EOF
    fi

    if [ "$VIM_MODE" = "full" ]; then
        if [ -d "$OFFLINE_DIR/vundle" ]; then
            run_cmd "创建 Vundle 目录" mkdir -p "$TARGET_HOME/.vim/bundle"
            remove_path "$TARGET_HOME/.vim/bundle/vundle"
            copy_path "$OFFLINE_DIR/vundle" "$TARGET_HOME/.vim/bundle/vundle"
        elif [ "$ALLOW_ONLINE_FETCH" -eq 1 ]; then
            run_cmd "在线克隆 Vundle" git clone https://gitee.com/hzx_3/vundle.git "$TARGET_HOME/.vim/bundle/vundle"
        fi

        if [ "$INSTALL_VIM_PLUGINS" -eq 1 ] && [ -f "$TARGET_HOME/.vimrc" ]; then
            try_shell "安装 Vim 插件" "su - '$TARGET_USER' -c \"vim +'BundleInstall' +qall >/dev/null 2>&1\""
        fi
    fi

    if [ "$TARGET_USER" != "root" ] && [ "${DRY_RUN:-0}" -eq 0 ]; then
        chown -R "$TARGET_USER:$TARGET_USER" "$TARGET_HOME/.vim" "$TARGET_HOME/.vimrc" 2>/dev/null || true
    fi
}
